### ISSUE TITLE
Syntax Error when requiring firebase

### ISSUE THREAD

**Issue by swatisinghi** [oscardelben/firebase-ruby#41]
I am getting this syntax error when doing a require 'firebase'
```
localhost ~/firebase $ irb
1.8.7-p374 :001 > require 'rubygems'
 => true 
1.8.7-p374 :002 > require 'firebase'
SyntaxError: /usr/local/rvm/gems/ruby-1.8.7-p374/gems/firebase-0.2.3/lib/firebase/request.rb:7: syntax error, unexpected ':', expecting ')'
      @client = HTTPClient.new(base_url: base_uri)
                                        ^
/usr/local/rvm/gems/ruby-1.8.7-p374/gems/firebase-0.2.3/lib/firebase/request.rb:34: syntax error, unexpected ':', expecting ')'
...(method, "#{path}.json", body: body, query: query_options, f...
                              ^
/usr/local/rvm/gems/ruby-1.8.7-p374/gems/firebase-0.2.3/lib/firebase/request.rb:34: syntax error, unexpected ':', expecting '='
...ath}.json", body: body, query: query_options, follow_redirec...
                              ^
/usr/local/rvm/gems/ruby-1.8.7-p374/gems/firebase-0.2.3/lib/firebase/request.rb:34: syntax error, unexpected ':', expecting '='
...uery_options, follow_redirect: true)
                              ^
	from /usr/local/rvm/rubies/ruby-1.8.7-p374/lib/ruby/site_ruby/1.8/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
	from /usr/local/rvm/rubies/ruby-1.8.7-p374/lib/ruby/site_ruby/1.8/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/rvm/gems/ruby-1.8.7-p374/gems/firebase-0.2.3/lib/firebase.rb:2
	from /usr/local/rvm/rubies/ruby-1.8.7-p374/lib/ruby/site_ruby/1.8/rubygems/core_ext/kernel_require.rb:135:in `gem_original_require'
	from /usr/local/rvm/rubies/ruby-1.8.7-p374/lib/ruby/site_ruby/1.8/rubygems/core_ext/kernel_require.rb:135:in `require'
	from (irb):2
```

**Comment by thekendalmiller** [comment]
The latest version, v0.2.3, is using ruby 1.9 style hashes in some places.

I just took a quick look and v0.2.2 should still work on ruby 1.8.7

**Comment by vincentwoo** [comment]
latest version should be using 1.8.7 compatible syntax everywhere, now
